### ISSUE TITLE
Downloading GrondwaterFilters fails: XML cannot be parsed

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#191]
* PyDOV version: 0.2.1
* Python version: 3.6
* Operating System: Windows

### Description

Due to an issue in the DOV XML export application, XML of GrondwaterFilters is not exported correctly, and subsequently fails to be parsed in pydov.

This needs to be fixed in the DOV XML webservice, and afterwards pydov's XML cache might need to be removed.

I will follow up here when the issue is resolved.

### What I Did

```
fs = GrondwaterFilterSearch()

df_filters = fs.search(
    location=WithinDistance(Point(150000, 150000), 10000)
)

print(df_filters)
```

```
[000/046] cccccccccccccccccccccccccccccccccccccccccccccc
Traceback (most recent call last):
  File "C:/Projecten/PyDov/pydov_git/scratch.py", line 94, in <module>
    location=WithinDistance(Point(150000, 150000), 10000)
  File "C:\Projecten\PyDov\pydov_git\pydov\search\grondwaterfilter.py", line 150, in search
    return_fields),
  File "C:\Projecten\PyDov\pydov_git\pydov\types\abstract.py", line 545, in to_df_array
    unnest_result(res.get(), df_result)
  File "c:\program files (x86)\python36-32\Lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "c:\program files (x86)\python36-32\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Projecten\PyDov\pydov_git\pydov\types\abstract.py", line 611, in get_df_array
    self._parse_xml_data()
  File "C:\Projecten\PyDov\pydov_git\pydov\types\abstract.py", line 283, in _parse_xml_data
    func=tree.findtext,
AttributeError: 'NoneType' object has no attribute 'findtext'
```

**Comment by Roel** [comment]
The issue is fixed serverside.

Should the issue persist on your local pydov installation, this probably means the XML cache still contains invalid documents. You can resolve this by remove the cache by issuing the following statement:

```python
pydov.cache.remove()
```
