### ISSUE TITLE
field 'eerste_invoer' gives an error when using it in a .search query in the option return_fields=

### ISSUE THREAD

**Issue by d16408** [DOV-Vlaanderen/pydov#382]
* PyDOV version: 2.2.0
* Python version: 3.7.6
* Operating System: Windows 10 Enterprise

### Description

Compared to the documentation  an additional field 'eerste_invoer' is seen at boringen, sonderingen and grondwaterfilters. This field gives an error message  when it is used in a .search query, in the option return_fields=.

### What I Did

```
from pydov.search.boring import BoringSearch
boring = BoringSearch()
fields = boring.get_fields()
for f in fields.values():
    print(f['name'])
#additional field 'eerste_invoer' compared to the documentation (https://pydov.readthedocs.io/en/stable/notebooks/search_boringen.html)

alle_velden=tuple(d['name'] for d in fields.values())
from pydov.util.location import Within, Box
df = boring.search(location=Within(Box(153145, 206930, 153150, 206935)),return_fields=alle_velden)

# solution: alle_velden=tuple(d['name'] for d in fields.values() if d['name'] != 'eerste_invoer')

```
Traceback (most recent call last):

  File "<ipython-input-89-e5a930e553cb>", line 10, in <module>
    df = boring.search(location=Within(Box(153145, 206930, 153150, 206935)),return_fields=alle_velden)

  File "C:\Users\d16408\AppData\Roaming\Python\Python37\site-packages\pydov\search\abstract.py", line 850, in search
    data=self._type.to_df_array(features, return_fields),

  File "C:\Users\d16408\AppData\Roaming\Python\Python37\site-packages\pydov\types\abstract.py", line 617, in to_df_array
    for item in iterable:

  File "C:\Users\d16408\AppData\Roaming\Python\Python37\site-packages\pydov\types\abstract.py", line 434, in from_wfs
    yield (cls.from_wfs_element(ft, namespace))

  File "C:\Users\d16408\AppData\Roaming\Python\Python37\site-packages\pydov\types\abstract.py", line 391, in from_wfs_element
    returntype=field.get('type', None)

  File "C:\Users\d16408\AppData\Roaming\Python\Python37\site-packages\pydov\types\abstract.py", line 69, in _parse
    return cls._typeconvert(text, returntype)

  File "C:\Users\d16408\AppData\Roaming\Python\Python37\site-packages\pydov\search\abstract.py", line 80, in _typeconvert
    return typeconvert(text)

  File "C:\Users\d16408\AppData\Roaming\Python\Python37\site-packages\pydov\search\abstract.py", line 72, in typeconvert
    x.split('.')[0], '%Y-%m-%dT%H:%M:%S')

  File "C:\Users\d16408\.conda\envs\environment_dov\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)

  File "C:\Users\d16408\.conda\envs\environment_dov\lib\_strptime.py", line 362, in _strptime
    data_string[found.end():])

ValueError: unconverted data remains: +01:00

**Comment by Roel** [comment]
Thank you for your report. This is indeed expected: `eerste_invoer` is a datetime field and these are only fully supported as of pydov 3.0.0.

If you use pydov 2.x you can exclude them as you mentioned, but it is better to filter on type instead of name (although `eerste_invoer` is the only datetime field for now):
```python
alle_velden = tuple(d['name'] for d in fields.values() if d['type'] != 'datetime')
```

**Comment by Roel** [comment]
I will close this ticket since this can be avoided by using the latest pydov release.

Don't hesitate to reopen if this is not an option for you, or if you encounter another problem!
